import { ClerkProvider } from '@clerk/nextjs'
import { Metadata } from 'next';
import React from 'react'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    manifest: '/manifest.webmanifest'
};
const RootLayout = ({
    children
}: {
    children: React.ReactNode
}) => {
    return (
        <ClerkProvider>
            <html lang='en'>
                <body>
                    {children}
                    <Toaster />
                </body>
            </html>
        </ClerkProvider>
    )
}

export default RootLayout
